config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    post '/orders_list_actions', to: 'base#orders_list_actions'
  end
end

app/models/spree/order_decorator.rb
Spree::Order.class_eval do
  def self.to_csv(orders, max_order_items)
    csv = []
    orders.each do |order|
      row = [order.completed_at.try(:strftime, "%m/%d/%Y"), order.number, "Donation", order.shipments.map(&:shipping_method).compact.map(&:name).uniq.join(", "), order.email, order.name, order.shipping_address.try(:company), order.shipping_address.try(:address1), order.shipping_address.try(:address2), order.shipping_address.try(:city), order.shipping_address.try(:state).try(:name), order.shipping_address.try(:zipcode), order.shipping_address.try(:country).try(:name), "0", order.line_items.count, order.total.to_s, order.item_total.to_s, order.shipments.map(&:cost).sum.to_s, order.shipments.map(&:cost).sum.to_s, nil] # TODO Comments
      order.line_items.each do |li|
        row << li.sku
        row << li.quantity
        row << nil #TODO Attributes
        row << li.price.to_s
      end
      remaining_items = max_order_items - order.line_items.count
      row << [""] * remaining_items * 4

      csv << row.flatten
    end
    csv
  end
end

app/controllers/spree/admin/base_controller_decorator.rb
Spree::Admin::BaseController.class_eval do
  def orders_list_actions
    require 'csv'
    orders_list = if params[:orders_list]
      params[:orders_list]
    else
      Spree::Order.all.pluck(:id)
    end
    orders = Spree::Order.where(id: orders_list)
    orders = orders.where(state: params[:state]) unless params[:state].empty?
    orders = orders.where(payment_state: params[:payment_state]) unless params[:payment_state].empty?
    orders = orders.where(shipment_state: params[:shipment_state]) unless params[:shipment_state].empty?

    orders = orders.order("updated_at DESC")

    # orders = Spree::Order.all
    all_orders = if orders.is_a?(Hash)
      orders.map {|k, v| v}.flatten
    else
      orders
    end
    headers = ["Order Date", "Order #", "Type", "Shipping Method", "Email", "Name", "Company", "Address 1", "Address 2", "City", "State", "Zip", "Country", "Weight (oz)", "Total Items", "Order Total", "Subtotal", "Handling", "Shipping", "Comments"]
    max_order_items = all_orders.map(&:line_items).map(&:size).max
    if !max_order_items.nil?
      max_order_items.times do |i|
        headers << "Item #{i+1} SKU"
        headers << "Item #{i+1} Qty"
        headers << "Item #{i+1} Attributes"
        headers << "Item #{i+1} Price"
      end



      full_csv = CSV.generate do |csv|
        csv_array = []
        csv_array << headers
        if orders.is_a?(Hash)
          orders.each do |day, v|
            csv_array << [day]
            csv_array += Spree::Order.to_csv(v, max_order_items)
          end
        else orders.is_a?(Array)
          csv_array += Spree::Order.to_csv(orders, max_order_items)
        end
        csv_array.each  do |csv_row|
          csv << csv_row
        end
      end
      send_data full_csv, :filename => 'orders.csv'
    else
      redirect_to :back
      flash[:error] = "No orders found!"
    end
  end
end

app/controllers/spree/admin/orders_controller_decorator.rb
Spree::Admin::OrdersController.class_eval do
  def orders_list_actions
    require 'csv'
    orders_list = if params[:orders_list]
      params[:orders_list]
    else
      Spree::Order.all.pluck(:id)
    end
    orders = Spree::Order.where(id: orders_list)
    orders = orders.where(state: params[:state]) unless params[:state].empty?
    orders = orders.where(payment_state: params[:payment_state]) unless params[:payment_state].empty?
    orders = orders.where(shipment_state: params[:shipment_state]) unless params[:shipment_state].empty?

    orders = orders.order("updated_at DESC")

    # orders = Spree::Order.all
    all_orders = if orders.is_a?(Hash)
      orders.map {|k, v| v}.flatten
    else
      orders
    end
    headers = ["Order Date", "Order #", "Type", "Shipping Method", "Email", "Name", "Company", "Address 1", "Address 2", "City", "State", "Zip", "Country", "Weight (oz)", "Total Items", "Subtotal", "Handling", "Shipping", "Comments"]
    max_order_items = all_orders.map(&:line_items).map(&:size).max
    if !max_order_items.nil?
      max_order_items.times do |i|
        headers << "Item #{i+1} SKU"
        headers << "Item #{i+1} Qty"
        headers << "Item #{i+1} Attributes"
        headers << "Item #{i+1} Price"
      end



      full_csv = CSV.generate do |csv|
        csv_array = []
        csv_array << headers
        if orders.is_a?(Hash)
          orders.each do |day, v|
            csv_array << [day]
            csv_array += Spree::Order.to_csv(v, max_order_items)
          end
        else orders.is_a?(Array)
          csv_array += Spree::Order.to_csv(orders, max_order_items)
        end
        csv_array.each  do |csv_row|
          csv << csv_row
        end
      end
      send_data full_csv, :filename => 'orders.csv'
    else
      redirect_to :back
      flash[:error] = "No orders found!"
    end
  end

end

app/views/spree/admin/orders/_order_list_actions.html.erb
<%= form_tag(admin_orders_list_actions_path, method: :post) do %>
    <%= render_original %>
    <h1>Export Orders to CSV</h1>
    <p>Either check off the order's above you would like exported, or all orders will be considered selected. To narrow down the orders you would like to export, select from the fields below.</p>
    <div id='list_state_change' class='field'>
    <%= label_tag nil, Spree.t(:state) %>
    <br>
    <%= select_tag :state, options_for_select([['Choose State', ''], ['Cart', 'cart'], ['Address', 'address'], ['Delivery', 'delivery'], ['Payment', 'payment'], ['Confirm', 'confirm'], ['Complete', 'complete']]), :class => 'select2' %>

    <div id='list_payment_state_change' class='field'>
    <%= label_tag nil, Spree.t(:payment_state) %>
    <br>
    <%= select_tag :payment_state, options_for_select([['Choose State', ''], ['Paid', 'paid'], ['Balance_due', 'balance_due'], ['Credit_owed', 'credit_owed'], ['Failed', 'failed']]), :class => 'select2' %>

    <div id='list_shipment_state_change' class='field'>
    <%= label_tag nil, Spree.t(:shipment_state) %>
    <br>
    <%= select_tag :shipment_state, options_for_select([['Choose State', ''], ['Shipped', 'shipped'], ['Partial', 'partial'], ['Ready', 'ready'], ['Backorder', 'backorder'], ['Pending', 'pending']]), :class => 'select2' %>
    <br />
    <br />
    <br />
    <%= button_tag 'Export as csv', {id: 'export_orders_btn','onclick' => '$(\"#order_action_export\").val(\"export\");'} %>

  </div>
  <%= hidden_field_tag 'order_action_export' %>
  <%= hidden_field_tag 'order_action_state' %>
  <%= hidden_field_tag 'order_action_payment_state' %>
  <%= hidden_field_tag 'order_action_shipment_state' %>
  <% end %>